### ISSUE TITLE
Increasing the number of sentences used in SMOG [request]

### ISSUE THREAD

**Issue by rbamos** [cdimascio/py-readability-metrics#10]
According to the [Wikipedia article for smog](https://en.wikipedia.org/wiki/SMOG), the SMOG score can be generalized beyond 30 sentences. It seems like that might be a valuable for increasing the accuracy of the metric, since computational time is much cheaper than human eyeball time (which the metric was originally designed for).

I'm happy to submit a PR if you think it's valuable.

**Comment by cdimascio** [comment]
@rbamos  Thanks! Please do.

**Comment by rbamos** [comment]
Committed PR #11, closing this issue
