### ISSUE TITLE
Dale-Chall Formula

### ISSUE THREAD

**Issue by susmoy-macgill36** [cdimascio/py-readability-metrics#15]
Hi,

In dale_chall.py,

`percent_difficult_words =  stats.num_dale_chall_complex / stats.num_words * 100`
` if percent_difficult_words > .05`

Why .05? Is it not 5? Kindly pardon me if  I am wrong.

Thank you.

**Comment by cdimascio** [comment]
Thanks @susmoy-macgill36,You are correct. Would u mind submitting a PR with the change. Once done I'll release a new package version

**Comment by susmoy-macgill36** [comment]
Okay, thank you for your response.

**Comment by cdimascio** [comment]
you're fix is in the `v1.4.5`. thanks!
