### ISSUE TITLE
pypi package release 1.4.1 is downloading 1.3.5

### ISSUE THREAD

**Issue by GrilledChickenThighs** [cdimascio/py-readability-metrics#7]
I just found this package and did a fresh install from pypi with the latest version, but the package version is showing 1.3.5.
I uninstalled the package and tried to reinstall with `pipenv install py-readability-metrics==1.4.1`
The version is still showing 1.3.5
I then downloaded the tar.gz from pypi and looked inside the package, but could not find the data folder. 
It looks like this package was just uploaded a few days ago, not sure why it's not downloading the correct version from pypi. The setup.py looks ok, but I'm not sure why pypi won't let me download the latest version.

As a result I am getting this error.

`FileNotFoundError: [Errno 2] No such file or directory: 'lib/python3.7/site-packages/readability/text/../data/spache_easy_porterstem.txt'
`
Apparently this file was added in the newest release, so it makes sense that it's not being found since my 1.3.5 version only contains dale_chall_porterstem.txt

**Comment by cdimascio** [comment]
Thanks @GrilledChickenThighs. seems like an oversight on my end when publishing the new version. could you give v1.4.2 a try?

**Comment by GrilledChickenThighs** [comment]
> Thanks @GrilledChickenThighs. seems like an oversight on my end when publishing the new version. could you give v1.4.2 a try?

Works now! Thanks for the quick fix @cdimascio That was super fast.

**Comment by cdimascio** [comment]
excellent!
